# Site settings
title: Artificial Intelligence and Statistics Conference
description: > # this means to ignore newlines until "baseurl:"
  This is the website of the AISTATS 2023 conference.
baseurl: "/aistats2023" # the subpath of your site, e.g. /blog/
timezone: EST

# If you want to create a twitter account for your conference include
# twitter name here
twitter_username: 

github_username:  aistats

author:
  name: AISTATS
  # YOu might want to create an email for handling conference queries, e.g. aistats20XX@gmail.com. If you do, you can enter it here.
  email: aistats2023@gmail.com
comments: false

# Build settings
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
# change encoding for the generated output files to utf-8
encoding: utf-8
remote_theme: lawrennd/proceedings
style: aistats

ghub:
  edit: true
  repository: aistats2023


# Place a banner image in assets/images and give its name here.
banner: white.png 

conference:
  full_name: Artificial Intelligence and Statistics
  short_name: AISTATS
  name: Artificial Intelligence and Statistics
  # set to True if the programme is draft only.
  draft: true
  # set to True to hide tentative speakers
  hide_tentative: true 
  # Place an image of venue in assets/images and give its name here
  image: conference-venue.png
  proceedings:
    # When proceedings are published add url here.
    url:      
    show: false
  # Give details of the room in the venue here.  
  room:
  # Set the name of the venue (e.g. Caribe Hilton Hotel)  
  venue: TBD.
  # Give the url of the venue here.  
  venue_url:
  # Give the conference location in the form City, Country here.
  location: Valencia, Spain.
  year: 2023
  # Give the instance of the conference here (e.g. 24th)
  instance:
  # Styling for AISTATS is "International Conference"  
  styling: International Conference on
  # Give the individual days that the conference will be held on here.
  dates:
  - Spring 2023
  - 
  # Give the submission site details here.
  submission:
    # Whether to show the submission site.
    show: true
    # The URL of the submission site.
    url: https://cmt3.research.microsoft.com/AISTATS2023
    # The name of the submission site (e.g. Microsoft CMT Website)
    name: Microsoft CMT
  deadlines:
    # Fill in the key dates as below.
    - name: Abstract submission deadline
      text: 6 October 2022 (Anywhere on Earth)
      type: submission
    - name: Paper submission deadline
      text: 13 October 2022 (Anywhere on Earth)
      type: submission
    - name: Supplementary materials submission deadline
      text: 20 October 2022 (Anywhere on Earth)
      type: submission
    - name: Reviews released to authors
      date: 21 November 2022
    - name: Author rebuttal deadline
      text: 5 December 2022 (Anywhere on Earth)
      type: submission
    - name: Paper decision notifications
      date: 19 January 2023
      type: decision
  # List program chairs here.      
  chairs:
  - type: General Chair
    people:
    - family: Ruiz
      given: Francisco
      # Give their personal web page.  
      url: https://franrruiz.github.io/
      institute: DeepMind
  - type: Program Chairs
    people:
    - family: Dy
      given: Jennifer
      # Give their personal web page.  
      url: https://ece.northeastern.edu/fac-ece/jdy/
      institute: Northeastern University
    - family: van de Meent
      given: Jan-Willem
      url: https://jwvdm.github.io
      institute: University of Amsterdam
  - type: Workflow Chairs
    people:
    - family: Hill
      given: Davin
      url: https://www.davinhill.me/
      institute: Northeastern University
    - family: Naesseth
      given: Christian
      url: https://naesseth.github.io/
      institute: University of Amsterdam
  - type: Sponsorship Chair
    people:
    - family: Mandt
      given: Stephan
      url: http://www.stephanmandt.com/
      institute: UC Irvine
  - type: Communications Chairs
    people: 
    - family: Makar
      given: Maggie
      url: https://mymakar.github.io/
      institute: University of Michigan
    - family: Izmailov
      given: Pavel
      url: https://izmailovpavel.github.io/
      institute: New York University
  - type: Diversity and Inclusion Chair
    people: 
    - family: Williamson
      given: Sinead
      url:  https://sinead.github.io/
      institute: UT Austin
  - type: Publication Chair
    people: 
    - family: Geffner
      given: Tomas
      url: https://people.umass.edu/tgeffner/
      institute: UMass Amherst
  - type: Local Chair
    people: 
    - family: Fernández-Torres
      given: Miguel-Ángel
      url: https://miguelangelft.github.io/
      institute: Universitat de València
  - type: Volunteer Chair
    people: 
    - family: Fernández-Torres
      given: Miguel-Ángel
      url: https://miguelangelft.github.io/
      institute: Universitat de València
  # You might want Workflow Chair(s) to assist with your submission system and the review process.     
