# Site settings
title: Artificial Intelligence and Statistics Conference
description: > # this means to ignore newlines until "baseurl:"
  This is the website of the AISTATS 20XX conference.
baseurl: "/aistats2023" # the subpath of your site, e.g. /blog/

# If you want to create a twitter account for your conference include
# twitter name here
twitter_username: 

github_username:  aistats

author:
  name: AISTATS
  # YOu might want to create an email for handling conference queries, e.g. aistats20XX@gmail.com. If you do, you can enter it here.
  email: 
comments: false

# Build settings
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
# change encoding for the generated output files to utf-8
encoding: utf-8
remote_theme: lawrennd/proceedings
style: aistats

ghub:
  edit: true
  repository: aistats2023


# Place a banner image in assets/images and give its name here.
banner: resort.png 

conference:
  full_name: Artificial Intelligence and Statistics
  short_name: AISTATS
  name: Artificial Intelligence and Statistics
  # set to True if the programme is draft only.
  draft: true
  # set to True to hide tentative speakers
  hide_tentative: true 
  # Place an image of venue in assets/images and give its name here
  image: conference-venue.png
  proceedings:
    # When proceedings are published add url here.
    url:      
    show: false
  # Give details of the room in the venue here.  
  room:
  # Set the name of the venue (e.g. Caribe Hilton Hotel)  
  venue: Hybrid In-person and Virtual
  # Give the url of the venue here.  
  venue_url:
  # Give the conference location in the form City, Country here.
  location: United States of America (location TBD)
  year: 2023
  # Give the instance of the conference here (e.g. 24th)
  instance:
  # Styling for AISTATS is "International Conference"  
  styling: International Conference on
  # Give the individual days that the conference will be held on here.
  dates:
  - Spring 2023
  - 
  # Give the submission site details here.
  submission:
    # Whether to show the submission site.
    show: true
    # The URL of the submission site.
    url: https://cmt3.research.microsoft.com/AISTATS2023
    # The name of the submission site (e.g. Microsoft CMT Website)
    name: Microsoft CMT
  deadlines:
    # Fill in the key dates as below.
    - name: Submission server open
      type: submission
      date: 15 September 2022
    - name: Paper submission deadline
      type: submission
      time: 13 October 2022
    - name: Author response period starts
      date: 28 November 2022
    - name: Author response period ends
      time: 9 December 2022
    - name: Paper decision notifications
      date: 19 January 2023
      type: decision
    - name: Deadline for camera-ready papers
      time: 23 February 2023
    - name: Registration deadline
      date: 
  # List program chairs here.      
  chairs:
  - type: Program Chairs
    people:
    - family: Dy
      given: Jennifer
      # Give their personal web page.  
      url: https://ece.northeastern.edu/fac-ece/jdy/
      institute: Northeastern University
    - family: van de Meent
      given: Jan-Willem
      url: https://jwvdm.github.io
      institute: University of Amsterdam and Northeastern University
  # If there's a local chair, or a general chair, you can add them here.
  - type: Local Chair
    people:
    - family: 
      given: 
      url: 
      institute:
  # You might want Workflow Chair(s) to assist with your submission system and the review process.     
  - type: Workflow Chairs
    people:
    - family: Hill
      given: Davin
      url: https://www.davinhill.me/
      institute: Northeasten University
    - family: Naesseth
      given: Christian
      url: https://naesseth.github.io/
      institute: University of Amsterdam
  # Your Publication Chair handles processing of proceedings.      
  - type: Publication Chair
    people:
    - family: 
      given: 
      url: 
      institute:
  # Publicity Chairs often handle websites, social media etc.      
  - type: Publicity Chair
    people:
    - family: 
      given: 
      url: 
      institute:
  # D&I Chairs look after initiatives to ensure an inclusive conference      
  - type: D&I Chair
    people:
    - family: 
      given: 
      url: 
      institute:
  # Sponsorship chairs handle bringing in money from sponsors.      
  - type: Sponsorship Chair
    people:
    - family: 
      given: 
      url: 
      institute: 
